package com.agon.app.data

import android.content.Context
import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "silina_profiles")

/**
 * Server Profile Data Model
 */
@Serializable
data class ServerProfile(
    val id: String,
    val name: String,
    val m3uUrl: String,
    val serverUrl: String,
    val username: String,
    val password: String,
    val isActive: Boolean = false,
    val isAutoGenerated: Boolean = false
)

/**
 * ProfileRepository - Manages up to 3 server profiles
 * 
 * Features:
 * - Stores up to 3 server profiles maximum
 * - Provides wipe functionality for clearing all profiles
 * - Uses DataStore for persistence
 */
class ProfileRepository private constructor(private val context: Context) {
    
    private val json = Json { ignoreUnknownKeys = true }
    
    companion object {
        private val PROFILES_KEY = stringPreferencesKey("saved_profiles")
        private const val MAX_PROFILES = 6
        
        @Volatile
        private var INSTANCE: ProfileRepository? = null
        
        fun getInstance(context: Context): ProfileRepository {
            return INSTANCE ?: synchronized(this) {
                val instance = ProfileRepository(context.applicationContext)
                INSTANCE = instance
                instance
            }
        }
    }
    
    /**
     * Gets all saved profiles as a Flow
     */
    fun getAllProfiles(): Flow<List<ServerProfile>> {
        return context.dataStore.data.map { preferences ->
            val profilesJson = preferences[PROFILES_KEY] ?: "[]"
            try {
                json.decodeFromString<List<ServerProfile>>(profilesJson)
            } catch (e: Exception) {
                emptyList()
            }
        }
    }
    
    /**
     * Saves a list of profiles (max 6)
     * Automatically truncates if more than 6 are provided
     */
    suspend fun saveProfiles(profiles: List<ServerProfile>) {
        val cappedProfiles = profiles.take(MAX_PROFILES)
        context.dataStore.edit { preferences ->
            preferences[PROFILES_KEY] = json.encodeToString(cappedProfiles)
        }
    }

    /**
     * Saves auto-generated profiles while preserving existing manual profiles.
     * Deactivates all profiles first, then marks the first auto profile as active.
     */
    suspend fun saveAutoProfiles(newAutoProfiles: List<ServerProfile>) {
        val existing = getAllProfilesSync()
        val manualProfiles = existing.filter { !it.isAutoGenerated }
        val autoWithActive = newAutoProfiles.mapIndexed { index, p ->
            p.copy(isActive = (index == 0 && manualProfiles.isEmpty()))
        }
        // If no manual profiles, first auto is active; otherwise keep manual's active state
        val hasActiveManual = manualProfiles.any { it.isActive }
        val finalList = if (hasActiveManual) {
            manualProfiles.map { it.copy(isActive = true) } + autoWithActive.map { it.copy(isActive = false) }
        } else {
            manualProfiles + autoWithActive
        }
        saveProfiles(finalList.take(MAX_PROFILES))
    }

    /**
     * Adds a manual profile (or updates if same serverUrl+username exists).
     * Preserves all existing auto-generated profiles.
     * Marks the new manual profile as active.
     */
    suspend fun addManualProfile(newProfile: ServerProfile) {
        val existing = getAllProfilesSync()
        // Remove any existing manual profile with same server+username
        val filtered = existing.filter {
            it.isAutoGenerated || !(it.serverUrl == newProfile.serverUrl && it.username == newProfile.username)
        }
        // Deactivate all, then activate the new manual profile
        val updated = filtered.map { it.copy(isActive = false) } + newProfile.copy(isActive = true, isAutoGenerated = false)
        saveProfiles(updated.take(MAX_PROFILES))
    }
    
    /**
     * Adds a single profile if under the limit
     * @return true if added, false if limit reached
     */
    suspend fun addProfile(profile: ServerProfile): Boolean {
        val currentProfiles = getAllProfilesSync()
        if (currentProfiles.size >= MAX_PROFILES) {
            return false
        }
        saveProfiles(currentProfiles + profile)
        return true
    }
    
    /**
     * WIPES all saved profiles
     */
    suspend fun wipeAllProfiles() {
        context.dataStore.edit { preferences ->
            preferences[PROFILES_KEY] = "[]"
        }
    }

    /**
     * Removes only auto-generated profiles, keeping manual ones
     */
    suspend fun removeAutoProfiles() {
        val existing = getAllProfilesSync()
        val manualOnly = existing.filter { !it.isAutoGenerated }
        saveProfiles(manualOnly)
    }
    
    /**
     * Sets a profile as active
     */
    suspend fun setActiveProfile(profileId: String) {
        val profiles = getAllProfilesSync()
        val updatedProfiles = profiles.map { 
            it.copy(isActive = it.id == profileId)
        }
        saveProfiles(updatedProfiles)
    }
    
    /**
     * Gets the active profile
     */
    fun getActiveProfile(): Flow<ServerProfile?> {
        return context.dataStore.data.map { preferences ->
            val profilesJson = preferences[PROFILES_KEY] ?: "[]"
            try {
                val profiles = json.decodeFromString<List<ServerProfile>>(profilesJson)
                profiles.find { it.isActive }
            } catch (e: Exception) {
                null
            }
        }
    }
    
    /**
     * Deletes a specific profile by ID
     */
    suspend fun deleteProfile(profileId: String) {
        val profiles = getAllProfilesSync()
        saveProfiles(profiles.filter { it.id != profileId })
    }
    
    /**
     * Checks if profile limit is reached
     */
    fun isLimitReached(): Flow<Boolean> {
        return context.dataStore.data.map { preferences ->
            val profilesJson = preferences[PROFILES_KEY] ?: "[]"
            try {
                val profiles = json.decodeFromString<List<ServerProfile>>(profilesJson)
                profiles.size >= MAX_PROFILES
            } catch (e: Exception) {
                false
            }
        }
    }
    
    /**
     * Gets profile count
     */
    fun getProfileCount(): Flow<Int> {
        return context.dataStore.data.map { preferences ->
            val profilesJson = preferences[PROFILES_KEY] ?: "[]"
            try {
                val profiles = json.decodeFromString<List<ServerProfile>>(profilesJson)
                profiles.size
            } catch (e: Exception) {
                0
            }
        }
    }
    
    /**
     * Sync version for internal use
     */
    private suspend fun getAllProfilesSync(): List<ServerProfile> {
        return try {
            context.dataStore.data.map { preferences ->
                val profilesJson = preferences[PROFILES_KEY] ?: "[]"
                try {
                    json.decodeFromString<List<ServerProfile>>(profilesJson)
                } catch (e: Exception) {
                    emptyList()
                }
            }.first()
        } catch (e: Exception) {
            emptyList()
        }
    }
}
